### ISSUE TITLE
Black artifacts with stock tethers

### ISSUE THREAD

**Issue by coballast** [philipswan/TetheredRing#24]
I suspect it has to do with the order of rendering and the alpha blending equation. As they say, a picture is worth a thousand words.

![Screenshot_2023-12-18_22-26-57](https://github.com/philipswan/TetheredRing/assets/29463033/69c5764b-ecb8-4f2e-98bf-e28fb6625465)

**Comment by coballast** [comment]
See coballast:fastEarthTransparency

**Comment by coballast** [comment]
Also the tethers are rendered in sections? I need to read the code more but this suggests that.

**Comment by philipswan** [comment]
Yes, the tether geometry is for one tether. You can adjust their width to make them overlap more or less with Engineering->tetherSpanOverlapFactor. I suspect that the renderer thinks the black tether is not in the scene because of where its center is located relative to the camera, so it is treating it differently. Could be a three.js bug. I've seen similar issues with tubes. See: https://youtu.be/4zx2S3IudbI

**Comment by philipswan** [comment]
There's a line in main.js // tempTetherMesh.renderOrder = 1 which will override the render order. It's not a general purpose fix, but it is useful sometimes for debugging or for making specific shots look better.

**Comment by coballast** [comment]
Hmmmm, I''m gonna read the code for how it sorts and clips objects. This really bothers me.

**Comment by philipswan** [comment]
Yes, if we can figure out how to fix this, I imagine that everyone in the three.js will be super psyched.

**Comment by coballast** [comment]
This only happens when earth is transparent.

**Comment by philipswan** [comment]
![image](https://github.com/philipswan/TetheredRing/assets/29994403/8c266890-3454-48cd-9cba-8d7145631e1d)
Tether blending over semi-transparent transit tube and main rings seems to be not quite right.

**Comment by coballast** [comment]
This issue appears to not present as of #32

**Comment by coballast** [comment]
I am closing this issue. It's interesting that removing those lines from the shader fixes the issue.
