### ISSUE TITLE
Fork Level Dependent Opacity

### ISSUE THREAD

**Issue by coballast** [philipswan/TetheredRing#26]
Add a contribution to opacity that is a function of how many times the tether cable has branched.

Some questions:

Should this contribution be uniform across a single branch? (Seems like it should be physically accurate).

What would be the physically correct function for describing the thickness at every level?

One other thing I've been wondering is how do the intermediate interpolated points get added to the tether strips for each branch. I've been looking through the code but can't find it. If the number of fork levels is set to 2, then the first segment from the earth's surface has 5 points, then 3 for the next 2 and so on.

**Comment by philipswan** [comment]
The cross-sectional area of the cable that splits at each fork, not the diameter. So with a 1:2 split, the new diameter will be sqrt(1/2) = .707 the old diameter. For the 1:5 split, the new diameter will be sqrt(1/5) = .45 the old diameter.

**Comment by philipswan** [comment]
The tethers are rendered from lines 567 to 634 in tethers.js. `for (let i = 0; i<=numTetherPoints-2; i++) {` is looping along the curve of the tether as if the tether had no forks. Forks are handled by the branches class inside the loop. Initially, there is one branch (the trunk) but as the outer loop progresses, branches are modified. The conditions `if ((i>0) && (Number.isInteger(Math.log2(numTetherPoints-i)))) { ` takes care of modifying the branches. The `branches.forEach((branch) => {` section adds the points to the tether strips.
